apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dp
  namespace: argo-doro
spec:
  replicas: 5
  selector:
    matchLabels:
      rabbit: doro
  template:
    metadata:
      labels:
        rabbit: doro
    spec:
      containers:
      - name: doro
        image: doro0704/project:doro
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: dockerauth
