apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dp
  namespace: argo-doro
spec:
  replicas: 5
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - name: blue
        image: doro0704/keduitlab:blue
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
